### ISSUE TITLE
Using Domain Adaptation in Different Manner.

### ISSUE THREAD

**Issue by nikeshnaik** [cookielee77/Domain-Adaptive-Text-Style-Transfer#2]
2 Questions: 

1.  Could I use this is to learn generic question style like Quora Questions? 
2.  use the source style to create questions for different specfic domain.?

Like preserve question style but generate new questions for domain.
How do I view Generated Text??

**Comment by cookielee77** [comment]
Probably not. It depends what the most stylized words in the dataset. Usually, it replaces the stylized words.
