### ISSUE TITLE
some needs if you are willing

### ISSUE THREAD

**Issue by mingxuan007** [cookielee77/Domain-Adaptive-Text-Style-Transfer#5]
hello Li, i'am sorry to disturb you. Can you provide the annotated dataset about ENRON and GYAFC ? since i can't obtain them in websites and i want to proceed some experiments with them.

**Comment by cookielee77** [comment]
ENRON parallel dataset is collected by Microsoft so it has some company license issue. We will let you know once we make it public. 

GYAFC you can download from here: https://github.com/raosudha89/GYAFC-corpus.
