### ISSUE TITLE
very thank you that can get your reply on the previous problem. I have another problem that hope can  get your reply

### ISSUE THREAD

**Issue by mingxuan007** [cookielee77/Domain-Adaptive-Text-Style-Transfer#6]
I'm sorry to disturb you again. I have another problem and done many experiments, however still don't get the solution. I want to consult whether the  configuration parameters for amazon corpus are different (I have tried different parameters to run, but the results and transferred sentences are bad), if the parameters are different, can you tell me specific configuration?

**Comment by cookielee77** [comment]
Amazon dataset is very noisy, usually the transferred quality is worse than Yelp. Additionally, you can try to adjust the rho (https://github.com/cookielee77/DAST/blob/master/config.py#L71) accordingly based on your content/style trade-off.

**Comment by mingxuan007** [comment]
Thank you for your reply, in the end i have a  question hope  to get answer -- if the corpus contains much noise, whether it is better to delete sentences with  relatively higher noise properties  for  our training.

**Comment by cookielee77** [comment]
You can, but it will be very difficult to determine which sentences are noise by automatic algorithms.

**Comment by mingxuan007** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cookielee77"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 中午11:51
收件人: "cookielee77/DAST"<DAST@noreply.github.com&gt;; 
抄送: "轩 ty"<1206111863@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cookielee77/DAST] very thank you that can get your reply on the previous problem. I have another problem that hope can  get your reply (#6)





 
You can, but it will be very difficult to determine which sentences are noise by automatic algorithms.
